# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Khinsider < Formula
  desc "Easily fetch videogame soundtracks from downloads.khinsider.com"
  homepage "https://utf9k.net"
  version "2.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/marcus-crane/khinsider/releases/download/v2.0.3/khinsider_2.0.3_darwin_arm64.tar.gz"
      sha256 "2563300bff87b3928e61e5c750281327171f56f21bcd2ec35005f3f9804b29b2"

      def install
        bin.install "khinsider"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/marcus-crane/khinsider/releases/download/v2.0.3/khinsider_2.0.3_darwin_amd64.tar.gz"
      sha256 "40b45d62e6c02ea09fb07c618a4795b0040239b00d62f51be8071260c28eb288"

      def install
        bin.install "khinsider"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/marcus-crane/khinsider/releases/download/v2.0.3/khinsider_2.0.3_linux_amd64.tar.gz"
      sha256 "c7f3d0f1985e474f8f31f2ac324f30075d2710fa4f7ca3c45a19615dbaf06ae8"

      def install
        bin.install "khinsider"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marcus-crane/khinsider/releases/download/v2.0.3/khinsider_2.0.3_linux_arm64.tar.gz"
      sha256 "7a20552247cda5f2d911d96c52eb3a00eac03e51c1ff8cfd96cb671b1c74847c"

      def install
        bin.install "khinsider"
      end
    end
  end
end
