# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opendog < Formula
  desc "A hacky translation layer that converts Datadog traces into OpenTelemetry Protobufs for use with Jaegar"
  homepage "https://utf9k.net"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marcus-crane/opendog/releases/download/v0.0.2/opendog_0.0.2_darwin_amd64.tar.gz"
      sha256 "2119592d3e87cef2be4556093772a08a408f22bb89eb4b88a904add5de1342e5"

      def install
        bin.install "opendog"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marcus-crane/opendog/releases/download/v0.0.2/opendog_0.0.2_darwin_arm64.tar.gz"
      sha256 "138567b427cae3cbe617d6461e3be69e6ff407556098a5031bc71880686f995a"

      def install
        bin.install "opendog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marcus-crane/opendog/releases/download/v0.0.2/opendog_0.0.2_linux_arm64.tar.gz"
      sha256 "d59c349807c7ae035730cd8ea641bbbfbd8b0eae7388ec804385a4d3a6aa6b81"

      def install
        bin.install "opendog"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/marcus-crane/opendog/releases/download/v0.0.2/opendog_0.0.2_linux_amd64.tar.gz"
      sha256 "05b17a172ebb1bb91e791dc141dee267f3ce5af678ddf3d2263fcea4ff4fc2a3"

      def install
        bin.install "opendog"
      end
    end
  end
end
