# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spanner < Formula
  desc "A minimal tool for visualising Datadog traces"
  homepage "https://github.com/marcus-crane/spanner"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/marcus-crane/spanner/releases/download/v1.0.1/spanner_1.0.1_darwin_arm64.tar.gz"
      sha256 "80c3044cdb5df6fb2de6f5233cb5e6925fdcf336caa4173e45a2ca1cc77c2c84"

      def install
        bin.install "spanner"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/marcus-crane/spanner/releases/download/v1.0.1/spanner_1.0.1_darwin_amd64.tar.gz"
      sha256 "2bb929c966d7805d47efacee0d83e4ca67c87db6091326a892ae68cc8ad904d0"

      def install
        bin.install "spanner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marcus-crane/spanner/releases/download/v1.0.1/spanner_1.0.1_linux_arm64.tar.gz"
      sha256 "c596fb89b90bffb5591edf361e54ac2cf94f417caac7da24a276b3cef0e98bd4"

      def install
        bin.install "spanner"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/marcus-crane/spanner/releases/download/v1.0.1/spanner_1.0.1_linux_amd64.tar.gz"
      sha256 "dbc0bb1a6104263371c0a5898a703c56eb5b18f1a2fb85c9ebde73140f072136"

      def install
        bin.install "spanner"
      end
    end
  end
end
